spring.datasource.url=jdbc:postgresql://localhost:5432/kutubxona
spring.datasource.username=postgres
spring.datasource.password=parol
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
